// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztiuksjdkrlfwdrkffew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0aXVrc2pka3JsZndkcmtmZmV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NDExMjYsImV4cCI6MjA3MDExNzEyNn0.vcU_JzWhWwTbhUm43Z-0TgxfcnegMbJgv6ChuujkjWE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});